language: go
go:
- '1.10'
cache:
  directories:
  - tools/bin
  - tools/pkg
script:
- go run -v mage.go all
- tools/bin/goveralls -coverprofile=cover.out -service=travis-ci
env:
  global:
  - CONCURRENT_LINTERS=1
  - LINTER_DEADLINE=180s
