// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package multihttp

import (
	"fmt"
	"strings"
)

const (
	// ClientCertParamNone is a ClientCertParam of type none.
	// Do not request a client certificate
	ClientCertParamNone ClientCertParam = "none"
	// ClientCertParamRequest is a ClientCertParam of type request.
	// Request a client certificate but do not verify
	ClientCertParamRequest ClientCertParam = "request"
	// ClientCertParamRequire is a ClientCertParam of type require.
	// Require a client certificate to be sent but do not verify
	ClientCertParamRequire ClientCertParam = "require"
	// ClientCertParamVerifyifgiven is a ClientCertParam of type verifyifgiven.
	// Verify any client certificate which is sent
	ClientCertParamVerifyifgiven ClientCertParam = "verifyifgiven"
	// ClientCertParamRequireandverify is a ClientCertParam of type requireandverify.
	// Require a valid client certificate
	ClientCertParamRequireandverify ClientCertParam = "requireandverify"
)

var ErrInvalidClientCertParam = fmt.Errorf("not a valid ClientCertParam, try [%s]", strings.Join(_ClientCertParamNames, ", "))

var _ClientCertParamNames = []string{
	string(ClientCertParamNone),
	string(ClientCertParamRequest),
	string(ClientCertParamRequire),
	string(ClientCertParamVerifyifgiven),
	string(ClientCertParamRequireandverify),
}

// ClientCertParamNames returns a list of possible string values of ClientCertParam.
func ClientCertParamNames() []string {
	tmp := make([]string, len(_ClientCertParamNames))
	copy(tmp, _ClientCertParamNames)
	return tmp
}

// ClientCertParamValues returns a list of the values for ClientCertParam
func ClientCertParamValues() []ClientCertParam {
	return []ClientCertParam{
		ClientCertParamNone,
		ClientCertParamRequest,
		ClientCertParamRequire,
		ClientCertParamVerifyifgiven,
		ClientCertParamRequireandverify,
	}
}

// String implements the Stringer interface.
func (x ClientCertParam) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ClientCertParam) IsValid() bool {
	_, err := ParseClientCertParam(string(x))
	return err == nil
}

var _ClientCertParamValue = map[string]ClientCertParam{
	"none":             ClientCertParamNone,
	"request":          ClientCertParamRequest,
	"require":          ClientCertParamRequire,
	"verifyifgiven":    ClientCertParamVerifyifgiven,
	"requireandverify": ClientCertParamRequireandverify,
}

// ParseClientCertParam attempts to convert a string to a ClientCertParam.
func ParseClientCertParam(name string) (ClientCertParam, error) {
	if x, ok := _ClientCertParamValue[name]; ok {
		return x, nil
	}
	return ClientCertParam(""), fmt.Errorf("%s is %w", name, ErrInvalidClientCertParam)
}

// MarshalText implements the text marshaller method.
func (x ClientCertParam) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ClientCertParam) UnmarshalText(text []byte) error {
	tmp, err := ParseClientCertParam(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ClientCertParam) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
