// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package multihttp

import (
	"fmt"
	"strings"
)

const (
	// ConfigParamTlscert is a ConfigParam of type tlscert.
	ConfigParamTlscert ConfigParam = "tlscert"
	// ConfigParamTlskey is a ConfigParam of type tlskey.
	ConfigParamTlskey ConfigParam = "tlskey"
	// ConfigParamTlsclientca is a ConfigParam of type tlsclientca.
	ConfigParamTlsclientca ConfigParam = "tlsclientca"
	// ConfigParamTlsclientcadir is a ConfigParam of type tlsclientcadir.
	ConfigParamTlsclientcadir ConfigParam = "tlsclientcadir"
)

var ErrInvalidConfigParam = fmt.Errorf("not a valid ConfigParam, try [%s]", strings.Join(_ConfigParamNames, ", "))

var _ConfigParamNames = []string{
	string(ConfigParamTlscert),
	string(ConfigParamTlskey),
	string(ConfigParamTlsclientca),
	string(ConfigParamTlsclientcadir),
}

// ConfigParamNames returns a list of possible string values of ConfigParam.
func ConfigParamNames() []string {
	tmp := make([]string, len(_ConfigParamNames))
	copy(tmp, _ConfigParamNames)
	return tmp
}

// ConfigParamValues returns a list of the values for ConfigParam
func ConfigParamValues() []ConfigParam {
	return []ConfigParam{
		ConfigParamTlscert,
		ConfigParamTlskey,
		ConfigParamTlsclientca,
		ConfigParamTlsclientcadir,
	}
}

// String implements the Stringer interface.
func (x ConfigParam) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ConfigParam) IsValid() bool {
	_, err := ParseConfigParam(string(x))
	return err == nil
}

var _ConfigParamValue = map[string]ConfigParam{
	"tlscert":        ConfigParamTlscert,
	"tlskey":         ConfigParamTlskey,
	"tlsclientca":    ConfigParamTlsclientca,
	"tlsclientcadir": ConfigParamTlsclientcadir,
}

// ParseConfigParam attempts to convert a string to a ConfigParam.
func ParseConfigParam(name string) (ConfigParam, error) {
	if x, ok := _ConfigParamValue[name]; ok {
		return x, nil
	}
	return ConfigParam(""), fmt.Errorf("%s is %w", name, ErrInvalidConfigParam)
}

// MarshalText implements the text marshaller method.
func (x ConfigParam) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ConfigParam) UnmarshalText(text []byte) error {
	tmp, err := ParseConfigParam(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ConfigParam) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// NetworkSchemeUnix is a NetworkScheme of type unix.
	NetworkSchemeUnix NetworkScheme = "unix"
	// NetworkSchemeUnixs is a NetworkScheme of type unixs.
	NetworkSchemeUnixs NetworkScheme = "unixs"
	// NetworkSchemeTcp is a NetworkScheme of type tcp.
	NetworkSchemeTcp NetworkScheme = "tcp"
	// NetworkSchemeTcps is a NetworkScheme of type tcps.
	NetworkSchemeTcps NetworkScheme = "tcps"
)

var ErrInvalidNetworkScheme = fmt.Errorf("not a valid NetworkScheme, try [%s]", strings.Join(_NetworkSchemeNames, ", "))

var _NetworkSchemeNames = []string{
	string(NetworkSchemeUnix),
	string(NetworkSchemeUnixs),
	string(NetworkSchemeTcp),
	string(NetworkSchemeTcps),
}

// NetworkSchemeNames returns a list of possible string values of NetworkScheme.
func NetworkSchemeNames() []string {
	tmp := make([]string, len(_NetworkSchemeNames))
	copy(tmp, _NetworkSchemeNames)
	return tmp
}

// NetworkSchemeValues returns a list of the values for NetworkScheme
func NetworkSchemeValues() []NetworkScheme {
	return []NetworkScheme{
		NetworkSchemeUnix,
		NetworkSchemeUnixs,
		NetworkSchemeTcp,
		NetworkSchemeTcps,
	}
}

// String implements the Stringer interface.
func (x NetworkScheme) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x NetworkScheme) IsValid() bool {
	_, err := ParseNetworkScheme(string(x))
	return err == nil
}

var _NetworkSchemeValue = map[string]NetworkScheme{
	"unix":  NetworkSchemeUnix,
	"unixs": NetworkSchemeUnixs,
	"tcp":   NetworkSchemeTcp,
	"tcps":  NetworkSchemeTcps,
}

// ParseNetworkScheme attempts to convert a string to a NetworkScheme.
func ParseNetworkScheme(name string) (NetworkScheme, error) {
	if x, ok := _NetworkSchemeValue[name]; ok {
		return x, nil
	}
	return NetworkScheme(""), fmt.Errorf("%s is %w", name, ErrInvalidNetworkScheme)
}

// MarshalText implements the text marshaller method.
func (x NetworkScheme) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *NetworkScheme) UnmarshalText(text []byte) error {
	tmp, err := ParseNetworkScheme(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *NetworkScheme) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
