---
name: Build and Test
"on":
  push:
    branches:
      - "*"
    tags:
      - v*
  pull_request:
    branches:
      - "*"
  workflow_call:
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - name: Check style
        run: go run mage.go style

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - name: Lint
        run: go run mage.go lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - name: Test
        run: go run mage.go test
      - name: Merge Coverage Files
        run: go run mage.go coverage
      - name: Coveralls
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: .cover.out
